// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
//
// ==============================================================

/***************************** Include Files *********************************/
#include "xhls_ip.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XHls_ip_CfgInitialize(XHls_ip *InstancePtr, XHls_ip_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XHls_ip_Start(XHls_ip *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_ip_ReadReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_AP_CTRL) & 0x80;
    XHls_ip_WriteReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XHls_ip_IsDone(XHls_ip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_ip_ReadReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XHls_ip_IsIdle(XHls_ip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_ip_ReadReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XHls_ip_IsReady(XHls_ip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_ip_ReadReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XHls_ip_EnableAutoRestart(XHls_ip *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_ip_WriteReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XHls_ip_DisableAutoRestart(XHls_ip *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_ip_WriteReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XHls_ip_Get_return(XHls_ip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_ip_ReadReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_AP_RETURN);
    return Data;
}

void XHls_ip_Set_input_a(XHls_ip *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_ip_WriteReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_INPUT_A_DATA, Data);
}

u32 XHls_ip_Get_input_a(XHls_ip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_ip_ReadReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_INPUT_A_DATA);
    return Data;
}

void XHls_ip_Set_input_b(XHls_ip *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_ip_WriteReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_INPUT_B_DATA, Data);
}

u32 XHls_ip_Get_input_b(XHls_ip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_ip_ReadReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_INPUT_B_DATA);
    return Data;
}

void XHls_ip_Set_input_c(XHls_ip *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_ip_WriteReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_INPUT_C_DATA, Data);
}

u32 XHls_ip_Get_input_c(XHls_ip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_ip_ReadReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_INPUT_C_DATA);
    return Data;
}

void XHls_ip_Set_input_d(XHls_ip *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_ip_WriteReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_INPUT_D_DATA, Data);
}

u32 XHls_ip_Get_input_d(XHls_ip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_ip_ReadReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_INPUT_D_DATA);
    return Data;
}

void XHls_ip_Set_input_e(XHls_ip *InstancePtr, u32 Data) {
	Xil_AssertVoid(InstancePtr != NULL);
	Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

	XHls_ip_WriteReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_INPUT_E_DATA, Data);
}

u32 XHls_ip_Get_input_e(XHls_ip *InstancePtr) {
	u32 Data;

	Xil_AssertNonvoid(InstancePtr != NULL);
	Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

	Data = XHls_ip_ReadReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_INPUT_E_DATA);
	return Data;
}

void XHls_ip_Set_input_f(XHls_ip *InstancePtr, u32 Data) {
	Xil_AssertVoid(InstancePtr != NULL);
	Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

	XHls_ip_WriteReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_INPUT_F_DATA, Data);
}

u32 XHls_ip_Get_input_f(XHls_ip *InstancePtr) {
	u32 Data;

	Xil_AssertNonvoid(InstancePtr != NULL);
	Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

	Data = XHls_ip_ReadReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_INPUT_F_DATA);
	return Data;
}


void XHls_ip_InterruptGlobalEnable(XHls_ip *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_ip_WriteReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_GIE, 1);
}

void XHls_ip_InterruptGlobalDisable(XHls_ip *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_ip_WriteReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_GIE, 0);
}

void XHls_ip_InterruptEnable(XHls_ip *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XHls_ip_ReadReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_IER);
    XHls_ip_WriteReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_IER, Register | Mask);
}

void XHls_ip_InterruptDisable(XHls_ip *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XHls_ip_ReadReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_IER);
    XHls_ip_WriteReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_IER, Register & (~Mask));
}

void XHls_ip_InterruptClear(XHls_ip *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_ip_WriteReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_ISR, Mask);
}

u32 XHls_ip_InterruptGetEnabled(XHls_ip *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHls_ip_ReadReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_IER);
}

u32 XHls_ip_InterruptGetStatus(XHls_ip *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHls_ip_ReadReg(InstancePtr->Axilites_BaseAddress, XHLS_IP_AXILITES_ADDR_ISR);
}

